apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required - cloud"
  name: grafana
  namespace: kube-system
spec:
  rules:
    - host: grafana.v16.myvm.info
      http:
        paths:
          - backend:
              serviceName: monitoring-grafana
              servicePort: 80
            path: /

