apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: grafana
  namespace: kube-system
spec:
  rules:
    - host: grafana.k8s.myvm.info
      http:
        paths:
          - backend:
              serviceName: monitoring-grafana
              servicePort: 80
            path: /

