apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: helm
  namespace: kube-system
spec:
  rules:
    - host: helm.demo.myvm.info
      http:
        paths:
          - backend:
              serviceName: helm-dashboard
              servicePort: 80
            path: /

