apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: http-svc
spec:
  rules:
    - host: echo.svc.myvm.site
      http:
        paths:
          - backend:
              serviceName: http-svc
              servicePort: 80
            path: /

