apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: kibana
  namespace: logging
spec:
  rules:
    - host: kibana.demo.myvm.info
      http:
        paths:
          - backend:
              serviceName: kibana
              servicePort: 5601
            path: /

