apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: locust
  namespace: default
spec:
  rules:
    - host: locust.svc.myvm.site
      http:
        paths:
          - backend:
              serviceName: mottled-quetzal-master-svc
              servicePort: 8089
            path: /

