apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: monasca-grafana
  namespace: monitoring
spec:
  rules:
    - host: monasca-grafana.k8s1.myvm.info
      http:
        paths:
          - backend:
              serviceName: monasca-grafana
              servicePort: 3000
            path: /

