apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: scope-app
  namespace: kube-system
spec:
  rules:
    - host: scope.svc.myvm.site
      http:
        paths:
          - backend:
              serviceName: weave-scope-app
              servicePort: 80
            path: /

